Added support for ARM64 (just basic support) and i386.

diff --git a/appdir/znx b/appdir/znx
--- a/appdir/znx
+++ b/appdir/znx
@@ -13,7 +13,7 @@ shopt -s \
 set -eo pipefail
 
 _e () {
-	echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2;
+	echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2
 	exit 1
 }
 
@@ -99,7 +99,7 @@ _create_esp () {
 		$TMP_MNT/boot/grub
 
 	cp \
-		$PREFIX/bootx64.efi \
+		$PREFIX/*.efi \
 		$TMP_MNT/efi/boot
 
 	cp -r \
